roles:
  - name: "super user role name"
    permissions:
      - resource: /simple/api/challenge
        action: POST
      - resource: /simple/api/admin/*
        action: GET
      - resource: /simple/api/admin/*
        action: POST
      - resource: /simple/api/admin/*
        action: DELETE
      - resource: /simple/api/admin/*
        action: PUT
  - name: "other user role name"
    permissions:
      - resource: /simple/api/challenge
        action: POST
      - resource: /simple/api/v1/*
        action: GET
      - resource: /simple/api/v1/*
        action: POST
      - resource: /simple/api/v1/*
        action: DELETE
      - resource: /simple/api/v1/*
        action: PUT