roles:
  - name: "超级管理员"
    permissions:
      - resource: /{{ .ProjectConfig.UrlPrefix }}/api/challenge
        action: POST
      - resource: /{{ .ProjectConfig.UrlPrefix }}/api/admin/*
        action: GET
      - resource: /{{ .ProjectConfig.UrlPrefix }}/api/admin/*
        action: POST
      - resource: /{{ .ProjectConfig.UrlPrefix }}/api/admin/*
        action: DELETE
      - resource: /{{ .ProjectConfig.UrlPrefix }}/api/admin/*
        action: PUT
  - name: "管理员"
    permissions:
      - resource: /{{ .ProjectConfig.UrlPrefix }}/api/challenge
        action: POST
      - resource: /{{ .ProjectConfig.UrlPrefix }}/api/v1/*
        action: GET
      - resource: /{{ .ProjectConfig.UrlPrefix }}/api/v1/*
        action: POST
      - resource: /{{ .ProjectConfig.UrlPrefix }}/api/v1/*
        action: DELETE
      - resource: /{{ .ProjectConfig.UrlPrefix }}/api/v1/*
        action: PUT